name: geobenchmark-vector-ops
channels:
  - conda-forge
dependencies:
  - python=3.12
  # required
  - dask-geopandas
  - geofileops
  - geopandas-base
  - matplotlib-base
  # linting
  - mypy =1.18.2
  - pandas-stubs
  - pre-commit
  - ruff =0.14.4
  