name: geobenchmark-vector-ops
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  # required
  - dask-geopandas
  - geofileops
  - geopandas-base
  - matplotlib-base
  - pyogrio
  # linting
  - ruff
  - pre-commit