name: geobenchmark-zonalstats
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  # required
  - exactextract
  - geofileops
  - geopandas-base
  #- geowombat
  - matplotlib-base
  #- pygeoprocessing
  - rasterio
  #- rasterstats
  # linting
  - mypy =1.18.2
  - pre-commit
  - ruff =0.14.4