name: geobenchmark-zonalstats-qgis
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  # required
  - geofileops
  - geopandas-base
  - matplotlib-base
  - qgis
  # linting
  - mypy =1.18.2
  - pre-commit
  - ruff =0.14.4